version: '3'

services:
  partner:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5174:5174"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    networks:
      - app_network

networks:
  app_network:
    external: true
    name: sf-server_default