export enum SocketEventEnum {
  VET_REQUEST_CONSULTATION = 'VET:REQUEST_CONSULTATION',
  VET_CONSULTATION_SCHEDULED = 'VET:CONSULTATION_SCHEDULED',
  VET_CALL_INITIATE = 'VET:CALL_INITIATE',
  VET_CALL_INITIATE_WITH_CALL_ID = 'VET:CALL_INITIATE_WITH_CALL_ID',
  VET_END_CONSULTATION = 'VET:END_CONSULTATION',
  VET_CLOSE_CONSULTATION = 'VET:CLOSE_CONSULTATION',
  VET_CONSULTATION_CASE_UPDATED = 'VET:CONSULTATION_CASE_UPDATED',
  VET_ONLINE_STATUS_CHANGE = 'VET:ONLINE_STATUS_CHANGE',

  MEMBER_CANCEL_CONSULTATION = 'MEMBER:CANCEL_CONSULTATION',

  CASE_CREATED = 'CASE:CREATED',
  SESSION_ACCEPTED = 'SESSION:ACCEPTED',
  NOTIFICATION_CREATED = 'NOTIFICATION:CREATED',

  PARTNER_QUOTATION_SUBMITTED = 'PARTNER:QUOTATION_SUBMITTED',
  PARTNER_BOOKING_SCHEDULED = 'PARTNER:BOOKING_SCHEDULED',

  CASE_EMERGENCY_ESCALATION = 'CASE:EMERGENCY_ESCALATION',

  CTA_POPUP = 'CTA_POPUP',
}
