auth.token=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

defaults.url=https://sentry.io/
defaults.org=smoll-lo
defaults.project=smoll-app
# Using SENTRY_AUTH_TOKEN environment variable