export enum SocketEventEnum {
  VET_REQUEST_CONSULTATION = "VET:REQUEST_CONSULTATION",
  VET_CONSULTATION_SCHEDULED = "VET:CONSULTATION_SCHEDULED",
  VET_CALL_INITIATE = "VET:CALL_INITIATE",
  VET_END_CONSULTATION = "VET:END_CONSULTATION",
  VET_CLOSE_CONSULTATION = "VET:CLOSE_CONSULTATION",

  CASE_CREATED = "CASE:CREATED",
  SESSION_ACCEPTED = "SESSION:ACCEPTED",
  NOTIFICATION_CREATED = "NOTIFICATION:CREATED",
}
