export enum SocketEventEnum {
  VET_REQUEST_CONSULTATION = "VET:REQUEST_CONSULTATION",
  VET_CONSULTATION_SCHEDULED = "VET:CONSULTATION_SCHEDULED",
  VET_CALL_INITIATE = "VET:CALL_INITIATE",
  VET_END_CONSULTATION = "VET:END_CONSULTATION",
  VET_CLOSE_CONSULTATION = "VET:CLOSE_CONSULTATION",
  VET_CALL_INITIATE_WITH_CALL_ID = "VET:CALL_INITIATE_WITH_CALL_ID",

  CASE_CREATED = "CASE:CREATED",
  SESSION_ACCEPTED = "SESSION:ACCEPTED",
  NOTIFICATION_CREATED = "NOTIFICATION:CREATED",
  VET_ONLINE_STATUS_CHANGE = "VET:ONLINE_STATUS_CHANGE",

  PARTNER_QUOTATION_SUBMITTED = "PARTNER:QUOTATION_SUBMITTED"
}
