export enum SocketEventEnum {
  VET_CALL_REQUEST = "VET:CALL_REQUEST",
  VET_CALL_ACCEPT = "VET:CALL_ACCEPT",
  VET_CALL_REJECT = "VET:CALL_REJECT",

  CASE_CREATED = "CASE:CREATED",
  CASE_REJECTED = "CASE:REJECTED",

  SESSION_ACCEPTED = "SESSION:ACCEPTED",

  NOTIFICATION_CREATED = "NOTIFICATION:CREATED",
}
